# Generated by Django 3.0.2 on 2020-02-03 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traditional', models.CharField(max_length=30)),
                ('simplified', models.CharField(max_length=30)),
                ('english', models.CharField(max_length=200)),
                ('pinyin', models.CharField(max_length=50)),
                ('hsk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
                ('words', models.ManyToManyField(related_name='lists', to='vocab.Word')),
            ],
        ),
    ]
