# Generated by Django 3.0.2 on 2020-01-29 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='list',
            name='words',
        ),
        migrations.AddField(
            model_name='list',
            name='words',
            field=models.ManyToManyField(related_name='lists', to='vocab.Word'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
