# Generated by Django 3.0.2 on 2020-01-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_content', models.CharField(max_length=30)),
                ('english_content', models.CharField(max_length=200)),
                ('pinyin', models.CharField(max_length=50)),
                ('hsk_level', models.IntegerField()),
                ('is_name', models.BooleanField()),
            ],
        ),
    ]
