# Generated by Django 3.0.2 on 2020-01-24 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='chinese_content',
            new_name='characters',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='english_content',
            new_name='english',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='hsk_level',
            new_name='hsk',
        ),
    ]
