# Generated by Django 3.0.2 on 2020-01-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20200124_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='is_name',
        ),
    ]
