# Generated by Django 3.0.2 on 2020-01-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_remove_word_is_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='characters',
            new_name='simplified',
        ),
        migrations.AddField(
            model_name='word',
            name='traditional',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
